spring.application.name=pedidos-service
server.port=8083

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/cursos_db
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:Joseelmer31}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# URLs de Microservicios Colaboradores
services.auth.url=http://localhost:8081
services.cursos.url=http://localhost:8082

# Mercado Pago
mercadopago.access-token=TEST-8786075352621630-090217-974d9a4e1da3bffbdc3ec6f5dcdabbf8-3130074680
mercadopago.back-url.success=http://localhost:8080/pago/exito
mercadopago.back-url.failure=http://localhost:8080/pago/fallo
mercadopago.back-url.pending=http://localhost:8080/pago/pendiente
