server.port=8080
spring.application.name=gateway-service

# Rutas del API Gateway hacia los 3 microservicios
spring.cloud.gateway.mvc.routes[0].id=auth-service
spring.cloud.gateway.mvc.routes[0].uri=http://localhost:8081
spring.cloud.gateway.mvc.routes[0].predicates[0]=Path=/api/auth/**

spring.cloud.gateway.mvc.routes[1].id=cursos-service
spring.cloud.gateway.mvc.routes[1].uri=http://localhost:8082
spring.cloud.gateway.mvc.routes[1].predicates[0]=Path=/api/cursos/**

spring.cloud.gateway.mvc.routes[2].id=pedidos-service
spring.cloud.gateway.mvc.routes[2].uri=http://localhost:8083
spring.cloud.gateway.mvc.routes[2].predicates[0]=Path=/api/pedidos/**
