--
-- PostgreSQL database dump
--

\restrict OEiT4SaEV34dErF7mxMfGEbWQvvCH66tCDICtd2n8K5gwo2XAvfkRMKhEsSmiAS

-- Dumped from database version 18.6
-- Dumped by pg_dump version 18.6

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: pedidos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.pedidos (
    id bigint NOT NULL,
    correo character varying(150) NOT NULL,
    curso_id bigint NOT NULL,
    estado character varying(30) NOT NULL,
    fecha_actualizacion timestamp(6) without time zone NOT NULL,
    fecha_registro timestamp(6) without time zone NOT NULL,
    nombre_curso character varying(150) NOT NULL,
    nombre_estudiante character varying(120) NOT NULL,
    telefono character varying(20) NOT NULL,
    CONSTRAINT pedidos_estado_check CHECK (((estado)::text = ANY ((ARRAY['REGISTRADO'::character varying, 'PENDIENTE_PAGO'::character varying, 'PAGADO'::character varying, 'CONFIRMADO'::character varying, 'CANCELADO'::character varying])::text[])))
);


ALTER TABLE public.pedidos OWNER TO postgres;

--
-- Name: pedidos_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.pedidos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pedidos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: pedidos; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.pedidos (id, correo, curso_id, estado, fecha_actualizacion, fecha_registro, nombre_curso, nombre_estudiante, telefono) FROM stdin;
1	miguel@gmail.com	1	PENDIENTE_PAGO	2026-08-22 00:23:32.102176	2026-08-22 00:20:27.531971	Desarrollo Web Integrado	Miguel Alarcon	999999999
\.


--
-- Name: pedidos_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.pedidos_id_seq', 1, true);


--
-- Name: pedidos pedidos_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pedidos
    ADD CONSTRAINT pedidos_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

\unrestrict OEiT4SaEV34dErF7mxMfGEbWQvvCH66tCDICtd2n8K5gwo2XAvfkRMKhEsSmiAS

